apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: release-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://git.example.com/platform/gitops-repo.git
        revision: main
        files:
          - path: releases/release/*.yaml
  template:
    metadata:
      name: '{{appName}}-release'
    spec:
      project: release
      destination:
        name: '{{cluster}}'
        namespace: '{{envName}}-{{appName}}'
      source:
        repoURL: https://git.example.com/platform/gitops-repo.git
        targetRevision: main
        path: 'charts/common-{{type}}'
        helm:
          valueFiles:
            - ../../apps/{{appName}}.yaml
            - ../../envs/{{envName}}.yaml
            - ../../clusters/{{cluster}}.yaml
            - ../../releases/{{envName}}/{{appName}}.yaml
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
